#!/bin/bash
shopt -s direxpand
shopt -s expand_aliases
if [ -f ~/.bashrc ]; then source ~/.bashrc; fi
if [ -f ~/.bash_profile ]; then source ~/.bash_profile; fi
if [ -f ~/.bash_alias ]; then source ~/.bash_alias; fi

export CCSNPHOME=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
export EXTBINARIES="$CCSNPHOME/extbinaries"
export PATH=$PATH:$EXTBINARIES:$EXTBINARIES/gatk-4.1.7.0/
source $CCSNPHOME/modules/checkVariables.sh
source $CCSNPHOME/modules/align.sh
source $CCSNPHOME/modules/bamprep.sh
source $CCSNPHOME/modules/callvariants.sh
source $CCSNPHOME/modules/callcore.sh
set -e
#usage: ccSNP -1 reads_R2.fastq -2 reads_R2.fastq -r reference.fasta
#software requirements
# FASTQC (better download and create alias), MULTIQC
# sudo apt install pandoc
#R packages: DADA2, rmarkdown, rmdformats, DT, dplyr, ggplot2, plotly, stringr, Biostrings
if [ "$1" == "" ];then
    printHelp
fi
actualfolder=$(pwd)
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -1|--forward|-forward)
    R1="$2"
    shift # past argument
    shift # past value
    ;;
    -2|--reverse|-reverse)
    R2="$2"
    shift # past argument
    shift # past value
    ;;
    -0|--single|-single)
    R0="$2"
    PAIRED="false"
    shift # past argument
    shift
    ;;
    -r|--reference|-reference)
    REFERENCE="$2"
    shift # past argument
    shift # past value
    ;;
    -a|--aligner|-aligner)
    ALIGNER="$2"
    shift # past argument
    shift # past value
    ;;
    -c|--caller|-caller|-scaler|--scaler)
    SCALLER="$2"
    shift # past argument
    shift # past value
    ;;
     -o|-output|--output)
    OUTPUT="$2"
    shift # past argument
    shift # past value
    ;;
    -q|-quality|--quality)
    QUALITY="$2"
    shift # past argument
    shift # past value
    ;;
    -p|-ploidy|--ploidy)
    PLOIDY="$2"
    shift # past argument
    shift # past value
    ;;
    -qc|-qualitycontrol|--qualitycontrol)
    MAKEQC=true
    shift # past argument
    ;;
    -gc|-gatkcycles|--gatkcycles)
    GCYCLES="$2"
    shift # past argument
    shift # past value
    ;;
    -F|-force|--force)
    FORCE=true
    shift # past argument
    ;;
    -ncc|-nocc|--nocc|--nocallcore)
    NOCC=true
    shift # past argument
    ;;
    -ni|-noin|--noin|--nointegrate)
    NOIN=true
    shift # past argument
    ;;
    -nc|-noclean|--noclean|--noClean)
    CLEAN=false
    shift # past argument
    ;;
    -rqc|--readqc|--rqc|--makeQC|--readQC|-mqc|--mqc)
    MAKEQC="true"
    shift
    ;;
    --debug)
    DEBUG=true
    set -ex
    shift # past argument
    ;;
    -h|--help|-?)
    printHelp
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

if [[ -n $1 ]]; then
    echo "the following argument lack of parameter: $1"
    exit
fi

##########################

checkVariables

##check output folder
##########################


if [ "$OUTPUT" == "" ];then
    OUTPUT="ccsnp"
fi

if [ -d "$OUTPUT" ];then
    if [ "$FORCE" == "false" ];then
        echo "$(tput setaf 1)ERROR: $OUTPUT directory already exist or use --force to continue (overwriting)"
        exit 1   
    fi
else
    mkdir -p $OUTPUT
fi
cd $OUTPUT

##########################

##executing module selected

#       "qc")
		if [ "$MAKEQC" == "true" ];then
          source $CCSNPHOME/modules/qc.sh
          #READS VARIABLE IS MADE IN CHECKVARIABLE FUNCTION, IT TAKE THE R1&R2 OR R0 AFTER CHECKING IF THEIR EXIST
          #qc $READS $QUALITY
        fi
#exit
 #      "align")
          align $ALIGNER $READS $REFERENCE $OUTPUT
        #########################
        #$BAMFILES is now available. The "align module" export all the bam files available after map steps.
        #########################
 #      "filterbam")
          bamprep $BAMFILES $REFERENCE $OUTPUT

        #########################
        #$BAMFILES now is updated containing filtered bams
        #########################
 #      "snpcall")
          callvariants $SCALLER $BAMFILES $REFERENCE $OUTPUT $PLOIDY $QUALITY

        ###########################
        # VCFFILES is now availbale.
        ###########################
 #      "callcore")
        if [ "$NOCC" != "true" ];then
            callcore $VCFFILES
        fi

        #Gather rresults
        cp ${OUTPUT}_2-bamprep/*.bam .
        cp ${OUTPUT}_3-callvariant/*vcf .

        if [ $CLEAN == "true" ];then
            rm -rf ${OUTPUT}_1-map
            rm -rf ${OUTPUT}_2-bamprep
            rm -rf ${OUTPUT}_3-callvariant
        fi

        #rm -rf $OUTPUT/${OUTPUT}_*



echo '
         ___     _,.--.,_
      .-~   ~--"~-.   ._ "-.
     /      ./_    Y    "-. \
    Y       :~     !         Y
    lq p    |     /   Done!  .|
 _   \. .-, l    /          |j
()\___) |/   \_/";          !
 \._____.-~\  .  ~\.      ./
            Y_ Y_. "vr"~  T
            (  (    |L    j  
            [nn[nn..][nn..]
        ~~~~~~~~~~~~~~~~~~~~~~~

'